Add missing loginlist arguments
storycraft/node-kakao pull request #446
Opened 2021-06-27 07:14 UTC by jinsung99

2021-06-29 05:44 UTC, jjangga0214 requested changes

2021-06-29 05:44 UTC, jjangga0214 commented on src/talk/client/talk-client-session.ts
> +      'maxIds': [],
항상 빈 배열만 가능하다는 뜻인가요? 

아니라면, 무슨 타입의 array 인지 명시할 수 있지 않을까요?

2021-07-02 07:21 UTC, nunnu1028 commented on src/talk/client/talk-client-session.ts
> +      'maxIds': [],
실제 PC 카카오톡에선 chatIds와 maxIds가 항상 []으로 들어가는 것 같습니다.

2021-07-03 05:06 UTC, storycraft commented
LOGINLIST에 몇몇 속성들을 생략한 이유는 해당 속성들이 더이상 사용되고 있지 않다고 판단했기 때문입니다. 다만 -203 에러가 생략된 속성들 때문이었음을 감안해 테스트후 merge 하도록 하겠습니다

2021-07-03 05:50 UTC, nunnu1028 commented
> LOGINLIST에 몇몇 속성들을 생략한 이유는 해당 속성들이 더이상 사용되고 있지 않다고 판단했기 때문입니다. 다만 -203 에러가 생략된 속성들 때문이었음을 감안해 테스트후 merge 하도록 하겠습니다

현재 PC 카카오톡에서도 이러한 속성들이 들어가고, 서버단에서 생략된 속성으로 인해 위조된 클라이언트인지 감별해낼수 있는 점을 생각해야 할 것 같습니다.

2021-07-04 06:19 UTC, merged