feat(request): export interfaces
storycraft/node-kakao pull request #466
Opened 2021-07-01 04:57 UTC by jjangga0214

라이브러리를 소비하는 측에서 `CommandResultDoneValue` 와 `CommandResultDoneVoid` 를 명시적으로 import 하는 것이 필요할 수 있습니다.

아주 간단한 예시를 생각해보겠습니다.

```ts
export async function loginByEmailAndPassword(
  authApiClient: AuthApiClient
) {
  const res = await authApiClient.login({
    email: process.env.KAKAOTALK_ACCOUNT_EMAIL as string,
    password: process.env.KAKAOTALK_ACCOUNT_PASSWORD as string,
  });
  if (!res.success) {
    throw new Error(
      `Web login by email and password failed with status: ${res.status}`
    );
  }
  return res;
}
```

node-kakao 를 소비하는 쪽에서 다음과 같은 간단한 facade pattern 을 export 한다고 가정해보겠습니다.
`AuthApiClient.login` 은 `AsyncCommandResult` 를 return 하지만, 컴파일러는 `loginByEmailAndPassword` 가 return 하는`success` 필드가 반드시 true 로 보장되는 것을 추론할 수 있고, `AsyncCommandResult` 대신 `CommandResultDoneValue` 로 추론합니다.

문제는 tsc 의 `--declaration` 옵션이 켜져 있으면, `CommandResultDoneValue` 을 import 하는 것이 가능해야 합니다. node-kakao 로붜 타입을 불러와야 type declaration file 을 작성할 수 있을텐데, node-kakao 가 export 를 안해주니 오류가 나는 것입니다.

실제 위 코드의 오류 메세지는 다음과 같습니다.

```
Return type of exported function has or is using name 'CommandResultDoneValue' from external module "/path/to/node_modules/node-kakao/dist/request/index" but cannot be named.ts(4058)
```

2021-07-02 06:30 UTC, nunnu1028 commented
저도 같은생각을 해본적이 있는데 PR은 안넣었는데 넣어주셨네요 :)

2021-07-03 04:28 UTC, storycraft commented
`CommandResultFailed`와 `CommandResultDoneValue`가 따로 나눠서 선언되어있는 이유는 별개 인터페이스 취급하기 위함이 아닌 단순히 `success` 값에 따라 `CommandResult` 객체의 `result` 속성 접근을 제한하기 위함입니다. 위 예시의 경우 `success`가 false인 경우 에러를 throw하기 때문에 `result`값만 반환하면 됩니다.

2021-07-03 05:01 UTC, storycraft requested changes
CommandResultDoneValue와 CommandResultDoneVoid를 export하는 것 보다 status 값과 result 값을 가질수 있는 별개의 인터페이스를 선언하고 export하는 것이 나아보입니다.

2021-07-04 06:18 UTC, storycraft commented
재확인 결과 `CommandResultDone`이 export 되고 있는 중 입니다. 해당 타입을 사용하세요.

2021-07-04 06:18 UTC, closed without merging